# SPDX-FileCopyrightText: 1998 Argonne National Laboratory
#
# SPDX-License-Identifier: EPICS

TOP=../..
include $(TOP)/configure/CONFIG

DB += lakeshore346_core.db
DB += lakeshore346_input.template
DB += lakeshore346_card.template
DB += lakeshore346_reconnect.db

include $(TOP)/configure/RULES
